// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:1047564837940:web:a0f8ef8271e4a3f6675661',
    messagingSenderId: '1047564837940',
    projectId: 'authtutorial-7a969',
    authDomain: 'authtutorial-7a969.firebaseapp.com',
    storageBucket: 'authtutorial-7a969.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:1047564837940:android:33c7de7567fbf15a675661',
    messagingSenderId: '1047564837940',
    projectId: 'authtutorial-7a969',
    storageBucket: 'authtutorial-7a969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:1047564837940:ios:43824d2b625c6684675661',
    messagingSenderId: '1047564837940',
    projectId: 'authtutorial-7a969',
    storageBucket: 'authtutorial-7a969.firebasestorage.app',
    iosBundleId: 'com.example.flutterfireAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:1047564837940:ios:43824d2b625c6684675661',
    messagingSenderId: '1047564837940',
    projectId: 'authtutorial-7a969',
    storageBucket: 'authtutorial-7a969.firebasestorage.app',
    iosBundleId: 'com.example.flutterfireAuth',
  );
}
